#!/bin/bash -l
# Standard output and error:
#SBATCH -o ./tjob.out.%j
#SBATCH -e ./tjob.err.%j
# Initial working directory:
#SBATCH -D ./
# Job Name:
#SBATCH -J <jobname>
# Queue (Partition):
# Number of nodes and MPI tasks per node:
#SBATCH --nodes=<nodes>
#SBATCH --ntasks-per-node=<ntaskspernode>
#
##SBATCH --mail-type=none
##SBATCH --mail-user=<userid>@rzg.mpg.de
#
# Wall clock limit:
#SBATCH --time=23:59:00

# Run the program:

OMP_NUM_THREADS=<nthread>; export OMP_NUM_THREADS
LD_LIBRARY_PATH=$MKL_HOME/lib/intel64_lin:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH

AIMS=/eos/u/igor1982/export/bin

aimsx="$AIMS/aims.<version>.x"

srun $aimsx > <joblog>

rm RUNNING
