#!/bin/csh -f
#filename : Aims_Environment
#Author:    Igor Ying Zhang
#Purpose:   Setting aims running environment and run aims
#
#Usage:     Aims_Environment Aims_Input

 setenv OMP_NUM_THREADS 1
 setenv AIMS /home/igor/Documents/Package-Pool/aims/bin
# setenv MPI  /home/igor/export/openmpi/bin
 setenv I_MPI_SHM_LMT shm

 set aimsx="$AIMS/aims.$2.x"

mpirun -n $1 $aimsx > $3

